import Head from "next/head";
import Image from "next/image";
import { Container, Main, Footer, Title } from "./Home.styles.js";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>
      </Main>

      <Footer>Stuff</Footer>
    </Container>
  );
}
